name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - name: Creer config.js
        run: |
          cat > js/config.js << EOF
          const GITHUB_CONFIG = {
              OWNER: 'Alexander-F2000',
              REPO: 'e-boutik',
              TOKEN: '${{ secrets.GH_CONTENT_TOKEN }}'
          };
          EOF
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v4
